# Generated by Django 2.2 on 2020-03-14 23:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userpetti',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userpetti',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='userpetti',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userpetti',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userpetti',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='userpetti',
            name='user',
        ),
        migrations.AddField(
            model_name='userpetti',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
