# Generated by Django 2.2 on 2020-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200314_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpetti',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
