# Generated by Django 2.2 on 2020-03-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20200314_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='tag',
            field=models.CharField(choices=[('adopcion', 'adopcion'), ('compra/venta', 'compra/venta'), ('parejas', 'parejas')], default=None, max_length=45),
            preserve_default=False,
        ),
    ]
