# Generated by Django 2.2 on 2020-03-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_publicacion_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tag',
            field=models.CharField(choices=[('adopcion', 'adopcion'), ('compra/venta', 'compraventa'), ('parejas', 'parejas')], max_length=45),
        ),
    ]
