# Generated by Django 2.2 on 2020-03-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpetti_ciudad'),
        ('mascotas', '0005_auto_20200315_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='owner',
        ),
        migrations.AddField(
            model_name='imagen',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserPetti'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserPetti'),
        ),
    ]
