# Generated by Django 2.2 on 2020-03-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_auto_20200319_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tag',
            field=models.CharField(choices=[('adopcion', 'adopcion'), ('compraventa', 'compraventa'), ('parejas', 'parejas')], max_length=45),
        ),
    ]
