# Generated by Django 2.2.10 on 2020-04-09 03:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Rol usuario',
                'verbose_name_plural': 'Rol usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCovid',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.CharField(max_length=45)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=120)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('rol_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.RolUsuario')),
            ],
            options={
                'verbose_name': 'Usuario Covid',
                'verbose_name_plural': 'Usuarios Covid',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
