# Generated by Django 2.2 on 2020-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='total_ventas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='vendidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('cancelado', 'cancelado'), ('entregado', 'entregado'), ('asignado', 'asignado')], max_length=45),
        ),
    ]
