# Generated by Django 2.2 on 2020-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200321_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('cancelado', 'cancelado'), ('entregado', 'entregado'), ('asignado', 'asignado')], default='pendiente', max_length=45),
        ),
    ]
