# Generated by Django 2.2 on 2020-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200321_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
