# Generated by Django 2.2 on 2020-03-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200321_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
