# Generated by Django 2.2 on 2020-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200325_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoindividual',
            name='color',
            field=models.CharField(max_length=12),
        ),
    ]
