# Generated by Django 2.2.10 on 2020-04-09 03:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.PositiveIntegerField()),
                ('identificacion', models.CharField(max_length=12)),
                ('tipo_persona', models.CharField(choices=[('Adulto mayor', 'Adulto mayor'), ('Desempleado', 'Desempleado'), ('Otro', 'Otro')], max_length=24)),
            ],
            options={
                'verbose_name': 'Reporte Covid',
                'verbose_name_plural': 'Reportes covid',
            },
        ),
        migrations.CreateModel(
            name='ReporteNecesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('tipo_persona', models.CharField(choices=[('Adulto mayor', 'Adulto mayor'), ('Desempleado', 'Desempleado'), ('Otro', 'Otro')], max_length=24)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='Activo', max_length=45)),
            ],
            options={
                'verbose_name': 'Reporte necesidad',
                'verbose_name_plural': 'Reporte necesidades',
            },
        ),
        migrations.CreateModel(
            name='TipoNecesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Necesidad',
                'verbose_name_plural': 'Necesidades',
            },
        ),
        migrations.CreateModel(
            name='UbicacionesNecesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=120)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('reporte_necesidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.ReporteNecesidad')),
            ],
            options={
                'verbose_name': 'Ubicacion necesidad',
                'verbose_name_plural': 'Ubicaciones necesidades',
            },
        ),
        migrations.CreateModel(
            name='UbicacionesCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=120)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('reporte_covid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.ReporteCovid')),
            ],
            options={
                'verbose_name': 'Ubicacion covid',
                'verbose_name_plural': 'Ubicaciones covid',
            },
        ),
        migrations.AddField(
            model_name='reportenecesidad',
            name='tipo_necesidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.TipoNecesidad'),
        ),
    ]
