# Generated by Django 2.2.10 on 2020-04-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_auto_20200328_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionescovid',
            name='reporte_covid',
        ),
        migrations.AddField(
            model_name='reportenecesidad',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Resuelto', 'Resuelto')], default='Activo', max_length=45),
        ),
        migrations.DeleteModel(
            name='ReporteCovid',
        ),
        migrations.DeleteModel(
            name='UbicacionesCovid',
        ),
    ]
